CREATE USER yachtsapp WITH PASSWORD 'pwd';

GRANT CONNECT ON DATABASE yachts TO yachtsApp;
GRANT USAGE ON SCHEMA public TO yachtsApp;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO yachtsApp;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO yachtsApp;
