DROP FUNCTION IF EXISTS UpdatePricesFunction(INT);
DROP FUNCTION IF EXISTS CalculateRevenueFunction(CHAR(10));
DROP FUNCTION IF EXISTS CalculateDiscountFunction(CHAR(10));
DROP FUNCTION IF EXISTS GetWaitingInvoicesFunction(DATE);

DROP FUNCTION IF EXISTS payInvoicesFunction(CHAR(10), INT, CHAR(4), DATE);

DROP TRIGGER IF EXISTS IssueInvoicesTrigger ON Rent;
DROP FUNCTION IF EXISTS IssueSingleInvoiceFunction(CHAR(10), INT, INT, DATE);
DROP FUNCTION IF EXISTS IssueWeekInvoicesFunction(CHAR(10), INT, INT, DATE, DATE);
DROP FUNCTION IF EXISTS IssueFiftyFiftyInvoicesFunction(CHAR(10), INT, INT, DATE, DATE);
DROP FUNCTION IF EXISTS IssueMonthlyInvoicesFunction(CHAR(10), INT, INT, DATE, DATE);
DROP FUNCTION IF EXISTS IssueInvoicesFunction();

DROP TRIGGER IF EXISTS AddRentTrigger ON Rent;
DROP TRIGGER IF EXISTS AddInspectionTrigger ON Inspection;
DROP FUNCTION IF EXISTS AddRentFunction();
DROP FUNCTION IF EXISTS AddInspectionFunction();
DROP FUNCTION IF EXISTS checkAvailable(INT, DATE);
DROP FUNCTION IF EXISTS checkTakenInspection(INT, DATE);
DROP FUNCTION IF EXISTS checkTakenRent(INT, DATE);

DROP VIEW IF EXISTS VBadRent;
DROP VIEW IF EXISTS VClientRentYacht;
DROP VIEW IF EXISTS VClientInvoice;
DROP VIEW IF EXISTS VInvoice;
DROP VIEW IF EXISTS VRent;
DROP VIEW IF EXISTS VClient;
DROP VIEW IF EXISTS VInspection;
DROP VIEW IF EXISTS VYacht;
DROP VIEW IF EXISTS VClass;

DROP TABLE IF EXISTS Invoice;
DROP TABLE IF EXISTS Rent;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Inspection;
DROP TABLE IF EXISTS Yacht;
DROP TABLE IF EXISTS Class;

REVOKE CONNECT ON DATABASE yachts FROM yachtsApp;
REVOKE ALL ON SCHEMA public FROM yachtsApp;
DROP ROLE IF EXISTS yachtsApp;
